config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "courses#index"
  resources :courses do 
  	resources :materials
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates :name, presence: true
	has_many :materials, dependent: :delete_all
end

app/models/material.rb
class Material < ApplicationRecord
	validates :name, presence: true
	belongs_to :course
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
	before_action :authenticate_user_or_admin, only: [:show]
	before_action :set_course, only: [:show, :edit, :update, :destroy]
	def index
		@courses = Course.all
	end

	def new
		@course = Course.new
	end

	def create
		@course = Course.new(course_params)
		if @course.save
			flash[:notice] = "Se ha creado el curso."
			redirect_to @course
		else
			flash[:error] = "No se ha creado el curso."
			render action: "new"
		end
	end

	def show
	end

	def edit
	end

	def update
		if @course.update(course_params)
			flash[:notice] = "Se ha actualizado el curso."
			redirect_to @course
		else
			flash[:error] = "No se ha actualizado el curso."
			render action: "edit"
		end
	end

	def destroy
		@course.destroy
		flash[:notice] = "El curso se ha eliminado."
		redirect_to courses_path
	end

	private
		def authenticate_user_or_admin
			if !admin_signed_in? and !user_signed_in?
				flash[:notice] = "Necesitar iniciar sesión para ver esta información."
				redirect_to root_url
			end
		end
		def set_course
			@course = Course.find(params[:id])
		end
		def course_params
			params.require(:course).permit(:name, :description)
		end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
	before_action :authenticate_admin!, only: [:new, :create, :edit, :update, :destroy]
	before_action :authenticate_user_or_admin, only: [:show]
	before_action :set_course
	before_action :set_material, only: [:show, :edit, :update, :destroy]
	before_action :set_s3_direct_post, only: [:new, :edit, :create, :update]

	def index
	end

	def new
		@material = @course.materials.build
	end

	def create
		@material = @course.materials.build(material_params)
		if @material.save
			flash[:notice] = "Se ha guardado el archivo."
			redirect_to @course
		else
			flash[:error] = "No se ha guardado el material."

			render action: "new"
		end
	end

	def show
		@material = @course.materials.find(params[:id])
	end

	def edit
		@material = @course.materials.find(params[:id])
	end

	def update
		if @material.update(material_params)
			flash[:notice] = "Se ha actualizado el material."
			redirect_to [@course, @material]
		else
			flash[:error] = "No se ha actualizado el material."

			render action: "edit"
		end
	end

	def destroy
		@material.destroy
		flash[:notice] = "El material se ha eliminado."
		redirect_to @course
	end

	private 
		def authenticate_user_or_admin
			if !admin_signed_in? and !user_signed_in?
				flash[:notice] = "Necesitar iniciar sesión para ver esta información."
				redirect_to root_url
			end
		end
		def set_course
			@course = Course.find(params[:course_id])
		end
		def set_material
			@material = @course.materials.find(params[:id])
		end
		def material_params
			params.require(:material).permit(:name, :description, :file)
		end

		def set_s3_direct_post
    		@s3_direct_post = S3_BUCKET.presigned_post(key: "uploads/#{SecureRandom.uuid}/${filename}", success_action_status: '201', acl: 'public-read')
  		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/courses/_form.html.erb
<%= form_for(@course) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br/>
	<%= f.label :description %>
	<%= f.text_area :description %><br/>
	<%= f.submit "Guardar" %>
<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<% if admin_signed_in? %>
	<%= link_to "Nuevo Curso", new_course_path %><br/>
<% end %>
<% if admin_signed_in? or user_signed_in? %>
	<% @courses.each do |course| %>
		<%= link_to course.name, course %><br/>
	<% end %>
<% end %>

app/views/courses/new.html.erb
<%= render 'form' %>

app/views/courses/show.html.erb
<h1><%= @course.name %></h1>
<% if admin_signed_in? %>
	<%= link_to "Añadir material", new_course_material_path(@course) %><br/>
	<%= link_to "Editar", edit_course_path(@course) %><br/>
	<%= link_to "Eliminar", course_path(@course), method: :delete, data: { confirm: "¿Estás seguro? Esta acción no se puede deshacer"} %><br/>
<% end %>
<p><%= @course.description %></p>

<% @course.materials.each do |material| %>
	<%= link_to material.name, [@course, material] %><br/>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cursify</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<% flash.each do |name, msg| %>
       <%= content_tag(:div, msg, class: "flash " + name) do %>
         <div><%= msg %></div>     
       <% end %>
    <% end %>
    <% if admin_signed_in? %>
      <%= link_to "Salir", destroy_admin_session_path %><br/><br/>
    <% end %>
     <% if user_signed_in? %>
      <%= link_to "Salir", destroy_user_session_path %><br/><br/>
    <% else %>
      <%= link_to "Iniciar Sesión", new_user_session_path %><br/><br/>
    <% end %>
    <%= yield %>

  </body>
</html>

app/views/materials/_form.html.erb
<%= form_for [@course, @material], html: { class: 'directUpload', data: { 'form-data': (@s3_direct_post.fields), 'url': @s3_direct_post.url, 'host': URI.parse(@s3_direct_post.url).host } } do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %><br/>
	<%= f.label :description %>
	<%= f.text_area :description %><br/>
	<%= f.label :file %>
	<%= f.file_field :file %><br/>
	<%= f.submit "Guardar" %>
<% end %>

<%= javascript_include_tag "/assets/forms/jquery.upload.widget" %>
<%= javascript_include_tag "/assets/forms/z.jquery.fileupload" %>
<%= javascript_include_tag "/assets/forms/forms" %>

app/views/materials/edit.html.erb
<%= render 'form' %>

app/views/materials/new.html.erb
<%= render 'form' %>

app/views/materials/show.html.erb
<h1><%= @material.name %></h1>

<%= link_to "Editar", edit_course_material_path(@course) %><br/>
<%= link_to "Eliminar", course_material_path(@course, @material), method: :delete, data: {confirm: "¿Estás seguro? Esta acción no se puede deshacer"} %><br/>
<p><%= @material.description %></p>

<% if !@material.file.include? ".png" and !@material.file.include? ".jpg" and !@material.file.include? ".jpeg" and !@material.file.include? ".gif" %>
	<%= link_to "Descargar", @material.file %><br/>
<% else %>
	<%= image_tag @material.file %><br/>
<% end %>